config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)

  root 'receipts#index'

  resources :uploads, only: [:new, :create]
  resources :products, only: [:index, :show]
  resources :receipts, only: [:index]

  get 'download' => 'download#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :receipts

  def display_name
    ref
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :receipt
  belongs_to :product

  scope :for_account, ->(account) { joins(:receipt).where(receipts: { account_id: account.id }) }
end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId
  friendly_id :stock_code
  has_many :line_items

  def line_items_for_account(account)
    line_items.for_account(account)
  end

  def total_inc_gst(account)
    line_items_for_account(account).sum(:total_inc_gst)
  end

  def average_time_between_purchases(account)
    # TODO: We should really base this on the earliest and latest time of all
    # the receipts
    earliest_time = account.receipts.minimum(:date)
    latest_time = account.receipts.maximum(:date)
    number = line_items_for_account(account).count
    ((latest_time - earliest_time) / number).round
  end
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  has_many :line_items, -> { order(:line_no) }
  belongs_to :account
  
  def total_inc_gst
    line_items.sum(:total_inc_gst)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  belongs_to :account

  delegate :receipts, to: :account, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def authenticate_active_admin_user!
    authenticate_user!
    unless current_user.admin?
      render text: "Not authorised", status: :forbidden
    end
  end

  protected

  def current_account
    current_user.account
  end
end

app/controllers/download_controller.rb
require "csv"

class DownloadController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    #@products = Product.where("stock_code != ''").order("CAST(stock_code AS int)").all
    @products = Product
      .where("stock_code != ''")
      .joins(line_items: :receipt)
      .where(receipts: { account_id: current_account.id })
      .group('products.id')
      .select('products.*, count(*) as count_all')
      .order('count_all desc')
      .all
  end

  def show
    @product = Product.friendly.find(params[:id])
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def index
    respond_to do |format|
      format.html do
        if current_user.receipts
          @receipts = current_user.receipts.order(:date => :desc).all
        else
          @receipts = Kaminari.paginate_array([])
        end
        @receipts = @receipts.page(params[:page])
      end

      format.csv do
        # Create a csv
        csv_string = CSV.generate do |csv|
          csv << ["Date (YYYY-MM-DD)", "Receipt code", "Product stock code", "Product description", "Quantity", "Total including GST"]
          current_account.receipts.order(date: :desc).find_each do |receipt|
            receipt.line_items.find_each do |l|
              csv << [receipt.date, receipt.code, l.product.stock_code, l.product.description, l.quantity, l.total_inc_gst]
            end
          end
        end
        send_data csv_string, :filename => "receipts.csv"
      end
    end
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
    unless current_user.admin?
      render text: "Unauthorized", status: :unauthorized
      return
    end
  end

  def create
    # TODO Extract filter
    unless current_user.admin?
      render text: "Unauthorized", status: :unauthorized
      return
    end
    csv_file = params[:export]
    CsvReader.load_csv(csv_file.path) do |hash|
      p hash
      account = Account.find_or_create_by(ref: hash["AccountRef"])
      # We're assuming that each receipt only ever has one account but let's double check that as
      # we go along and error if that isn't the case
      receipt = Receipt.find_by(code: hash["TransRefCode"])
      if receipt
        raise "Receipt has more than one date" unless receipt.date == Date.parse(hash["TransDate"])
        raise "Receipt has more than one account" unless receipt.account = account
      else
        receipt = Receipt.create(code: hash["TransRefCode"], date: Date.parse(hash["TransDate"]),
          account: account)
      end
      product = Product.find_or_create_by(stock_code: hash["StockCode"], description: hash["StockDesc"])
      LineItem.find_or_create_by(receipt: receipt, product: product,
        line_no: hash["DetailNo"], quantity: hash["LineQty"], total_ex_gst: hash["LineTotalExGST"],
        total_inc_gst: hash["LineTotalIncGST"])
    end

    redirect_to :root, flash: {alert: "Uploaded succesfully"}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def rough_period_of_time_in_words(days)
    if days >= 7
      weeks = days / 7.0
      if weeks.round >= 4
        months = weeks / 4.0
        pluralize(months.round, 'month')
      else
        pluralize(weeks.round, 'week')
      end
    else
      pluralize(days, 'day')
    end
  end

  def current_account
    current_user.account
  end

  def nav_item(item, link)
    active = current_page?(link)
    item_html = h(item)
    item_html += ' '.html_safe + content_tag(:span, '(current)'.html_safe, class: 'sr-only') if active
    content_tag(:li, link_to(item_html, link), class: ('active' if active))
  end
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/download/index.html.haml
.page-header
  %h1 Download

  %p.lead
    Download your shopping receipts data as a spreadsheet

%p
  This is <em>your</em> shopping data so <em>you</em> should have access to it to do
  with as you please. You could for example use it for
  %ul
    %li household budgetting
    %li seeing how much organic vs non-organic produce you buy
    %li what items you buy the most


%p
  You can load this into pretty much any spreadsheet program such as
  #{link_to "OpenOffice", "https://www.openoffice.org/"},
  #{link_to "Google Docs", "https://docs.google.com/spreadsheets"},
  or
  = link_to "Microsoft Office", "https://products.office.com"
  to do your own analysis. The data is downloaded as a
  = link_to "comma-separated values (CSV)", "http://en.wikipedia.org/wiki/Comma-separated_values"
  file which is very widely supported.

%p
  And please do let us know if you do something interesting with your data! We're
  always interested to hear from you.

= link_to "Download your data", receipts_path(format: "csv"), class: "btn btn-default"

app/views/layouts/application.html.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=edge', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1', name: 'viewport' }/
    / The above 3 meta tags *must* come first in the head; any other head
    / content must come *after* these tags
    %title Foodlist
    = stylesheet_link_tag 'application', media: 'all'
    %link{ href: 'http://fonts.googleapis.com/css?family=Copse', rel: 'stylesheet', type: 'text/css' }/
    / HTML5 shim and Respond.js for IE8 support of HTML5 elements and media
    / queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{ 'data-target' => '#bs-example-navbar-collapse-1', 'data-toggle' => 'collapse', type: 'button' }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Food List', root_path, class: 'navbar-brand'

        / Collect the nav links, forms, and other content for toggling
        .collapse.navbar-collapse#bs-example-navbar-collapse-1
          %ul.nav.navbar-nav
            = nav_item('Receipts', root_path)
            = nav_item('Products', products_path)
            - if current_user && current_user.admin?
              = nav_item('Upload', new_upload_path)
            = nav_item('Download', download_path)
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li= link_to('Logout', destroy_user_session_path, method: :delete)

    .container
      %p.notice= notice
      %p.alert= alert
      = yield
    = javascript_include_tag 'application'

app/views/products/index.html.haml
.page-header
  %h1 Products
  %p.lead
    -# Not actually strictly true at the moment
    All the things you can buy at the Coop

%table.table
  %thead
    %tr
      %th Stock Code
      %th Description
      %th You buy this roughly every
      %th Average spend / month
  %tbody
    - @products.each do |product|
      %tr
        %td= product.stock_code
        %td= link_to product.description, product
        %td= rough_period_of_time_in_words(product.average_time_between_purchases(current_account))
        %td= number_to_currency(product.total_inc_gst(current_account) / (current_account.receipts.maximum(:date) - current_account.receipts.minimum(:date)) * 28)

app/views/products/show.html.haml
.page-header
  %h1
    = @product.description
    %small= @product.stock_code

  %p.lead
    Every time you ever bought
    = @product.description.downcase
    at the Coop

  %p
    You buy this roughly every
    = rough_period_of_time_in_words(@product.average_time_between_purchases(current_account))

%table.table
  %thead
    %tr
      %th Date
      %th Quantity
      %th Price per unit
      %th Total
  %tbody
    - @product.line_items_for_account(current_account).order("receipts.date desc").each do |line_item|
      %tr
        %td
          = time_ago_in_words(line_item.receipt.date)
          ago
          (#{line_item.receipt.date.to_s(:long)})
        %td= line_item.quantity
        %td= number_to_currency(line_item.total_inc_gst / line_item.quantity)
        %td= number_to_currency(line_item.total_inc_gst)
    %tr
      %td
      %td
        %strong= @product.line_items_for_account(current_account).sum(:quantity)
      %td
      %td
        %strong= number_to_currency(@product.total_inc_gst(current_account))

app/views/receipts/index.html.haml
.page-header
  %h1 Receipts
  %p.lead See what you bought each time you visited the Coop

= paginate @receipts

- @receipts.each do |receipt|
  %div.panel.panel-default
    %div.panel-heading
      = time_ago_in_words(receipt.date)
      ago
      (#{receipt.date.to_s(:long)})

    %div.panel-body
      %table.table
        %thead
          %tr
            %th Quantity
            %th Description
            %th Total
        %tbody
          - receipt.line_items.each do |line_item|
            %tr
              %td= line_item.quantity
              %td= link_to_unless line_item.product.stock_code.empty?, line_item.product.description, line_item.product
              %td= number_to_currency(line_item.total_inc_gst)
          %tr
            %td
            %td
            %td
              %strong= number_to_currency(receipt.total_inc_gst)

app/views/uploads/new.html.haml
%p
  Do a csv export from the
  #{link_to "esuite software", "http://www.esuite.com.au/"} and then upload the file here

= form_tag({action: "create"}, multipart: true) do
  .form-group
    = file_field_tag 'export'
  = submit_tag("Upload", class: "btn btn-default")